### ISSUE TITLE
Text element starts out smaller than the minimum allowed size, creating strange behaviour

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#271]
This issue has been migrated from mozilla/webmaker-android#2373.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Tue Jun 30 2015 and had the following description:

> Steps to reproduce
> - Add a text element (needs to be 3 letters)
> - Start scaling it
> - Immediately it jumps up in size a little bit
> - You can't make it smaller than the size it jumped to
> - You can't make it as small as when you first added it to the page

**Comment by gvn** [comment]
I can't repro this anymore.

@flukeout are you still seeing this issue?

**Comment by flukeout** [comment]
Just to recap from yesterday, @gvn and I are both able to reproduce the issue. It happens more noticeably when the randomly added text content is short (like "Ola"). It makes the element smaller than our allowed minimum.

I think the best solution here would be to decrease the minimum size of these elements, so that neither the height nor the width can be smaller than 50px.
