### ISSUE TITLE
Add CTA to play mode for browsers [player]

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-core#295]
Design in https://github.com/mozilla/webmaker-browser/issues/154.

**Comment by k88hudson** [comment]
@gvn can you actually sync up with design/bobby today to make sure the implemented solution matches up with the intent for Android users/mobile users as well? It seems strange to me that there would be no link back to the playstore for mobile viewers

**Comment by gvn** [comment]
@secretrobotron @xmatthewx Now that this is [on staging](https://webmaker-desktop-staging.herokuapp.com/#/player?user=1&project=1), do you see any issues?

One thing that we may want to do is cookie the modal after "No thanks" is chosen so that it stays dismissed for future visits.

**Comment by xmatthewx** [comment]
@k88hudson - we didn't include link back for mobile users because the original plan was to auto redirect android users to the play store. For others on mobile, the link wouldn't be useful. 

We need to reconsider this given the new tech constraint ... this button in tandem with @vazquez's new "open in the app" notice. https://github.com/mozilla/webmaker-core/issues/322#issuecomment-122398545

**Comment by gvn** [comment]
Considering this done...
