### ISSUE TITLE
"Could not find page to load" error after deleting linked page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#336]
> Follow Link in button to off page open page "ghost" Which add buttons do not work
1. Create button
2. Create page for button to link to
3. Link button to that page
4. Delete that page
5. Go back to page that has the button, and edit it
6. Tap the button, and tap "Follow link"

Expected: "Follow link" to be "Set Destination"
Actual: 
- Error: "Could not find page to load"
- Able to go to "ghost" page, where you can add items, but they don't appear (weird / scary).

From https://etherpad.mozilla.org/webmaker-app-teste-fisl
cc @panaggio

**Comment by xmatthewx** [comment]
The unique bit in this bug is the ghost page where you can add elements. Blocking that by directing to set destination view would be a good interim solution. 

We've discussed cleaning up targets here: https://github.com/mozilla/webmaker-core/issues/210 and how to relabel UI in the editor for creators here: https://github.com/mozilla/webmaker-core/issues/190

**Comment by gvn** [comment]
This is fairly complicated actually. Link destinations are pulled from the database and usually don't have enough contextual data coming back with them to see if the destination still exists. For example: when the link editor webview is loaded, data is only pulled for the element being edited. We have no project data to examine for a greater context.

We may have to do additional XHR requests for the entirety of a project's data (and potentially still another request to see if a target project exists once we enable cross project linkage). This is a potential hit to load time performance.

Maybe I'm missing an easier solution here. Any ideas @k88hudson @Pomax ? Would it be crazy to have the server check that a destination is still valid as part of the element data request?

**Comment by xmatthewx** [comment]
Agreed. We should optimize for network performance _and_ perceived performance. Testing if link destinations exist on project load seems too aggressive; a user might tap zero links. Testing a link when it is tap will introduce a delay. 

Can we test links on a page when that page is opened? We could then keep the destination or prep an alert. In viewer, alert would be "Link destination not found [dismiss]". In editor, "Link destination not found [set destination] [dismiss]."

Does a link point to a page ID or a coordinate?

**Comment by gvn** [comment]
Just to clarify: there are only 2 views we need to check links on: the page view and the link editor view. Right now project view has links disabled, so it shouldn't be an issue there unless we re-enable them. It's less of a problem for project view, because the necessary data is available.

Testing links when a page is loaded is what I'm having problems with due to the lack of data about the entire project. I need to be able to parse all the pages in a project to see if the destination exists.

Links point to a page ID and a project ID (right now all project IDs are identical to the current project).

**Comment by gvn** [comment]
The more I consider it, we probably should fix this data on the server (with checks triggered by a request to the route in question). Non-existent link destinations could become an issue in other places as well, so it'd be nice to solve at the root level. Otherwise, our stored data is invalid and we're patching it on the client.

**Comment by gvn** [comment]
CC: @cadecairos – thoughts?

**Comment by k88hudson** [comment]
Since links are per-project only right now, couldn't we just walk through each link in the project view, and check it against the other pages in that project (no extra api call needed), and then display some alternative UI if the page doesn't exist? That should be enough to indicate to people they have to reset it, right?

We could additionally then _update_ that element to remove the broken link, so when you enter page edit mode, the "set link destination" thing shows again

**Comment by cadecairos** [comment]
I'm not sure this is something the server should even care about.

link data is just a bunch of arbitrary values placed into an elements attributes object, and will introduce unnecessary complexity if the the server is expected to validate and maintain it.

**Comment by gvn** [comment]
The project view isn't a problem: it's the link editor and page view that are missing the data I would need to traverse.

Aside from that, it's better to solve data integrity issues at the root level if possible.

**Comment by gvn** [comment]
Another possiblity: we could invalidate links when a page is removed on the client. This eliminates the need for the server to have to do extra validation work.

One caveat: This won't really work for cross-project link invalidation, but that's going to be another can of worms. :sweat:

**Comment by xmatthewx** [comment]
@gvn - Good thinking. That will have the least impact on real and perceived performance. (We can worry about links broken across projects if/when we actually have links across projects.)

**Comment by gvn** [comment]
I've been working on the approach of nullifying link destinations for dead pages when a page is deleted on the client. I've gotta say that I still don't think the client is the "correct" place to do this, but I can see how adding it to the existing service would also be cumbersome. It's kind of a middleware situation where a higher level of abstraction over the service feels appropriate to take the burden of mass data modeling off the client. If we do keep it in the client, I'd like to explore doing this deletion work in a module instead of inside the project view's `removePage` method.

Regardless, to add link destination nullification to the client without the bulk API endpoint in place will require an [XHR request](https://webmaker-api.herokuapp.com/docs?server=https://webmaker-api.herokuapp.com&path=/users/{user}/projects/{project}/pages/{page}#PATCH) to the service _for every single page in a project_ when a page is deleted. This means that the larger a project becomes, the longer page deletion will take. It's a pretty big performance issue...

I'd recommend that we consider this ticket blocked until the bulk API is completed.

Thoughts? @thisandagain @xmatthewx

**Comment by thisandagain** [comment]
I'm moving this to 1.2.0 to give us more time to hash out an approach as well as the connection to @Pomax 's bulk API work.

**Comment by gvn** [comment]
Blocked by https://github.com/mozilla/webmaker-core/issues/183

**Comment by gvn** [comment]
Instead of invalidating links, I took a more "webby" approach and just made a simple 404 view.
