### ISSUE TITLE
Text deleted when first editing text

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#346]
1. Add a text element
2. Edit it
3. Tap on text (or "Edit text" button) to change text
4. Type stuff

Expected: add to text that was already there
Actual: text is deleted

**Comment by secretrobotron** [comment]
Same happens on button.

**Comment by Pomax** [comment]
a request for clarification: which edit behaviour do we want on first edit, and which behaviour do we want on subsequent edits?

On first edit, we're offering a text field with a text that the user is almost guaranteed not interested in, so wiping that word once the user starts typing feels like it makes sense (although user feedback can invalidate that assumption).

Subsequent edits, however, should not wipe the word, since at that point we already have a string that the user clearly intended to stick around.

If I'm reading you correctly, you're suggesting we always respect the text that's already in a text box, and only ever let users "add" to that string (including "adding" backspaces) without clearing the input field in either use case?

**Comment by gvn** [comment]
Yeah, that makes sense to me too. What do you think @thisandagain ?

**Comment by thisandagain** [comment]
:+1: thanks for the clarification @Pomax. I agree that the text should be "wiped" on first edit but then persisted on any subsequent edit.

**Comment by xmatthewx** [comment]
This works for me. Selecting the text might be less jarring than wiping it, but either way, I agree that this should only happen to default text, not subsequent edits.

**Comment by Pomax** [comment]
in Android, selecting a text and then typing should wipe it, similar to how if you highlight a word on your regular computer and start typing, the highlighted word gets replaced. But, does that mean we're okay with the current behaviour (which means we can close https://github.com/mozilla/webmaker-core/pull/444), or do we need to change the behaviour (in which case https://github.com/mozilla/webmaker-core/pull/444 will likely need a rewrite)

**Comment by xmatthewx** [comment]
Let's go with #444 as written.
