### ISSUE TITLE
Occasionally losing edits between views

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#372]
**Repro Steps:**
1. Create new project 
2. Edit page
3. Add text
4. Hit back

**Expected:** Page edits are reflected in project overview
**Actual:** Sometimes they aren't. Possible race condition...

**Comment by gvn** [comment]
This also happens sometimes when editing elements and then hitting back. If I go back to the project overview sometimes I can see the edits I made, so it seems like they're getting persisted to the server, but not always updating in the client.

**Comment by Pomax** [comment]
the bulk-api rewrite will take care of the page <-> element oddities, since edits no longer go over the database but are synced to the database once you leave the page. However, I frequently see the project overview seemingly before the page write has apparently kicked in, so that the page looks different from what it was edited to be. Investigating why that might be atm.

**Comment by k88hudson** [comment]
This looks like a caching issue; `GET` requests seem to be returning old data. Looking into where we  need to fix this.

**Comment by k88hudson** [comment]
Should be fixed by https://github.com/mozilla/api.webmaker.org/issues/134 when that is resovled

**Comment by k88hudson** [comment]
Resolved by https://github.com/mozilla/api.webmaker.org/tree/4a544639387b6d0aa0310d379ebb069f1f112fd9
