### ISSUE TITLE
Rendering difference between browser and desktop

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#440]
This morning, I noticed a few discrepancies between page rendering on browser and the app. Problems seem to be persist across all browsers — including mobile ones.
#### App

This is how it should look:
![screenshot_2015-07-30-08-11-30](https://cloud.githubusercontent.com/assets/403231/8983090/29e88b14-3695-11e5-8b5a-f14b4d1166c3.png)

---
#### Chrome
- Text isn't always position properly
- Newlines in text where there shouldn't be

![screenshot 2015-07-30 08 12 20](https://cloud.githubusercontent.com/assets/403231/8983233/93c31d82-3696-11e5-9be8-9a2a0a083465.png)
![screenshot 2015-07-30 08 12 23](https://cloud.githubusercontent.com/assets/403231/8983231/93889fb8-3696-11e5-8873-95fe3b1ee552.png)
![screenshot 2015-07-30 08 12 26](https://cloud.githubusercontent.com/assets/403231/8983232/93af3a38-3696-11e5-9b6f-840b8bced33a.png)
#### Firefox (similar problems on mobile)
- Text can easily be cut off by the title bar
- Newlines where there shouldn't be
- Text positioning problems

<img width="1240" alt="q1ihi" src="https://cloud.githubusercontent.com/assets/403231/8983027/93d33e30-3694-11e5-9315-204525bdab3b.png">
<img width="1241" alt="wu3sa" src="https://cloud.githubusercontent.com/assets/403231/8983025/93bfc1b6-3694-11e5-9a03-0e726c9ac490.png">
![screenshot 2015-07-30 08 12 34](https://cloud.githubusercontent.com/assets/403231/8983189/1b5cea94-3696-11e5-99c4-13f1de069954.png)

**Comment by secretrobotron** [comment]
@thisandagain @xmatthewx not sure how to prioritize/assign this. Might be dupes at this point too.

**Comment by secretrobotron** [comment]
Link to project: https://beta.webmaker.org/#/player?user=454339&project=5721

**Comment by secretrobotron** [comment]
Update: looks perfect on mobile chrome.

**Comment by xmatthewx** [comment]
Seems like these are all related to font-size rendering differences (minor problem) triggering line breaks (major problem). I bet browsers handle fractional font sizes differently. 

Width on the text and link elements should allow for this variance so we can avoid line breaks.

**Comment by thisandagain** [comment]
:+1:

**Comment by thisandagain** [comment]
@gvn Could you take a look this week?

**Comment by gvn** [comment]
Our primary problem here is that all browsers render text differently. It's doubtful we'll ever get totally consistent layouts because of this. The same text with the same CSS will render at different widths depending on the layout engine, which means that line breaks won't always be in the same spots.

If you use something like `white-space: nowrap` that helps with consistency for single line text in our context, but breaks for multi-line cases.

One thing we may want to look into, but may be too extreme, is rendering text to canvas and storing it as an image (possibly base 64 encoded string) instead of live text. As long as we only have one editing engine then the result would stay consistent x-browser. This has a major drawback aside from complexity: bitmaps scale poorly and take up more bandwidth. De-serializing the rasterized text to an editable form is also tricky.

For now, I've opened a PR that forces width on text elements in Play mode to get _better_ consistency. It at least prevents some of the more extreme layout problems like what you're seeing in Firefox with each word on its own line.

**Comment by xmatthewx** [comment]
Are we using normalize.css or something similar? Besides that, let's keep this focused on the extreme layout failures like you suggest.  

It looks like Firefox has a bug on element width. A link and two of the phrases wrap much more than they should need to wrap.

**Comment by gvn** [comment]
A reset isn't going to solve the problem, but yes, we use one. Fundamentally, text is rendered differently at the engine level. I'm comparing identical CSS layouts across different layout engines and getting different dimensions for computed layout...

I have a PR to fix that FF layout so that it doesn't wrap on every word. There's a pretty crazy complex layout there and FF must need a little extra help.

**Comment by thisandagain** [comment]
Re: rendering using Canvas ... I'm wondering if 100% perfect accuracy across browsers is what we want. It doesn't quite feel "web-by" to me and so I'm curious if we should find some threshold for rendering inconsistency between browsers that we are comfortable with. Thoughts?

**Comment by gvn** [comment]
Yeah, the Canvas approach isn't something I'd advocate, but it's an option if consistency is paramount.

I agree that we should think in terms of a threshold for consistency. As we start introducing more advanced customization and features for projects we're going to be seeing more and more inconsistency cross-browser. That is the nature of the beast – we can only realistically smooth things out so much for user created content.

**Comment by xmatthewx** [comment]
Agreed. Variance is natural for web content. Not all pixels (or drop shadows) will align.

The unexpected line breaks cross a threshold for me. The app determines the relationship between element width and font-size, but needs more tolerance for expected variance. I see this as a bug rather than a user pushing the limits of the app or web content.

**Comment by Pomax** [comment]
practical limitation of canvas: putting text on a canvas takes up a LOT of memory, so trying to canvas-ise text can easily need an incidentally 20~30 MB even for a reasonably short bit of text, which on a mobile device is a terrible idea. And of course, it'd be content locking, which I'll always vote against because this is Mozilla, [it's not a thing we do](https://www.mozilla.org/en-US/about/manifesto/) =)

**Comment by gvn** [comment]
Ok, after discussing more in standup we're going to close this based on my forced width patch.
