### ISSUE TITLE
Poor button animations 

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#482]
When you add a button, its completely flat. There is no way to specify if you want a 3D button or if you want a flat button. The flat button has a really weird animation, it just jumps up and down and doesn't resemble like you're clicking anything at all.

**Comment by vazquez** [comment]
The button look has been fixed in https://github.com/mozilla/webmaker-core/issues/461

We added some bevel and border colour. There are no plans currently to allow the user to choose between a flat button and a raised button. We just decided to make them raised as default (they actually look like buttons now, not just bordered rectangles)
