### ISSUE TITLE
GA event tracking on page load

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#537]
Migrated from https://github.com/mozilla/webmaker-browser/issues/213

@adamlofting says:

See #207 
- [x] Are these events always recorded in GA?
- [x] Or, if GA hasn't fully loaded, do we silently miss tracking this data?

**Comment by xmatthewx** [comment]
How critical is this concern? Likely to fail often, or rarely? 

It would be valuable to compare shares on Android and the resulting views via Facebook etc. 

And, while the CTA in the browser says 'open app', for anyone who doesn't have the app, this leads to the play store and is a valuable conversion.

**Comment by adamlofting** [comment]
It won't cause any errors for the user, as it would fail silently.

But if we don't double check it, we could get incomplete data, and make bad decisions. The load order for JS isn't totally predictably, so the biggest risk is getting partial data and thinking we have complete data. (It's easier to notice when you get no data at all).

**Comment by thisandagain** [comment]
I can take a look at this today. For `webmaker-android` I know we are in good shape, but most certainly need to check on `webmaker-browser`.

**Comment by xmatthewx** [comment]
@thisandagain - is this something you can look at this week? Or should we reassign?

**Comment by thisandagain** [comment]
I was able to look at this on Friday. Tracking seems to be working just fine, but I'll take another look today (under load) to verify.

**Comment by adamlofting** [comment]
This tracking is working for the two events we're currently firing, but it's because GA is loading faster than the data from our API, even though we call the API first:

<img width="1359" alt="screenshot 2015-08-18 13 40 15" src="https://cloud.githubusercontent.com/assets/1901816/9330125/08780864-45af-11e5-90bd-1ff0cf6dfff4.png">

No urgent need to change anything here, but I'll file a bug to bump GA up in the load order of the player in case future tracking requires events to be tracked more quickly.

**Comment by thisandagain** [comment]
:+1:
