### ISSUE TITLE
Webmaker is generally quite slow and buggy

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-core#638]
This is not a specific bug, but a general comment on performance. We just did an event with kids today, and the app is quite slow and buggy. 

For example, I spent 20 min making a very simple quiz with a 12 years old.
- Pages disapeared a few times. They only reappeared  when exiting and re opening the app.
- After editing a link destination, there was a bug, when 5 minutes later we were editing text, and it thought we were still editing a button. The page was frozen. We again had to re-exit and re-opened.
- Position of elements moves when you change a page #637
- Some images appeared when in project view but they where inexistant in play view, but they are visible on desktop.

All of these ended up fixing themselves by re-opening the app, but the experience is frustrating.

Cc / @Saallen @xmatthewx @gvn @k88hudson

**Comment by ryanwarsaw** [comment]
As for the performance perspective, I think it will require an initiative by all of the engineers to evaluate the core architectural concepts we are using currently and determine area's where we can improve. Of course we will always have limitations due to our architectural decisions for Android (Java/JS bridge). 

However, I feel there are steps that can and will be taken to at least mitigate these problems to an extent on the Android side of things and I know that I will definitely be focusing on this area over the next couple of weeks. Here's a list of area's where I think we can improve and am working on.

1.) Identifying and fixing various RAM leaks that are currently occurring during the usage of the app, these are minimal but build up over time and need to be dealt with.

2.) Identifying areas of improvement in our caching system, I haven't done performance tests in comparison to other solutions, we should definitely make sure its running top notch.

3.) Identify where we can take advantage of the resources we have access to, take a multi-threaded approach where necessary, identify blocking code and streamline the process.

4.) Work on a much more simplistic router, our current one is fairly old, bloated and has many features we will never use, I've been working on a simpler solution that should be much faster and would also improve performance, (not dramatically however). 

5.) Re-write the Android platform, it seems pretty daunting but it would be well worth the time. It would allow us to clean up the code base and remove stuff we aren't using, as well as streamlining documentation and clean everything up. 

These are my opinions on ways we can improve performance and I'll be working towards these points over the next couple of weeks, (along with the migration to the new cache system).

**Comment by secretrobotron** [comment]
Thanks for the ideas, @ryanw-se. Should definitely discuss w/ the rest of the team.

@LauraReynal do you remember which devices they were using (even vaguely)?

**Comment by lauradereynal** [comment]
The bugs described above when we were making something with the 12 years old learner was a Nexus 5 
Other people used a Galaxy but I did not mentor that closely and I'm not able to describe with details

**Comment by gvn** [comment]
@xmatthewx can we break out any pertinent issues from this ticket into their own tickets and then close this one?

**Comment by xmatthewx** [comment]
@ryanw-se - let's file new tickets to align this with the plan you outlined in your list. And then close this.

**Comment by xmatthewx** [comment]
- tracking RAM leaks in #780. 
- tracking caching in #591 
- file new tickets for router and multi-threaded approaches if and when we have time to tackle them

closing
