### ISSUE TITLE
Elements are shifted in project viewer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#706]
all elements are shifted to the right by 5 to 10 px in project viewer as compared with project editor

**Comment by xmatthewx** [comment]
might just be text elements. and shift might be to the right and down.

**Comment by alanmoo** [comment]
Looks at least part of this is a result of #440's patch...investigating if there's another solution for that issue/if that's the only issue here. I notice that the actual page is slightly larger in project view compared to edit view, so if you're toggling between them elements will appear shift. However, they may actually still be in the same relative spot.

**Comment by xmatthewx** [comment]
Interesting. After you dig a bit more, let's evaluate our options before we dive toward a solution.

**Comment by alanmoo** [comment]
Further investigation reveals the #440 patch that caused this might have another solution- it appears that text elements are being rendered in `sans-serif` which will be different depending on the OS you're on. So using the project linked [there](https://beta.webmaker.org/#/player?user=454339&project=5721) as an example, forcing the `Roboto` font seems to solve a lot of problems. Everything looked right across Android browsers, because the system default for sans-serif is Robot, but not on Mac OS (and presumably it's broken on Windows too). We are loading those fonts from Google Fonts, though there's an HTTPS issue, as I noted in #733. In addition, buttons appear to be bigger in webmaker-browser projects because of some extra styles being applied to `.btn`, though that's an issue for that repo (and may be blocked until it's upgraded to React 0.14, which @gvn is working on at the moment.

**Comment by alanmoo** [comment]
@xmatthewx, please confirm that this is resolved?

**Comment by xmatthewx** [comment]
Let's good!
