### ISSUE TITLE
Snap to horizontal

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#714]
Project are a little bit askew. Users struggle to neatly place images and text. Snap to horizontal (+/-5º) will make this much easier.

**Comment by xmatthewx** [comment]
If on release, element is between -5º and +5º of horizontal, set to 0º.

**Comment by alanmoo** [comment]
Right now I've got this working so that as you drag, if it's close to zero (using a value that "feels" right), it snaps to zero until you drag farther. I'm thinking the behavior should be along the lines of "if I'm dragging towards zero and get close, jump to it" rather than on release, as changing the element after we release it is a.)not something we do elsewhere, and b.)more difficult given the way the code is written (since right now I can put the code inside the event handler vs more abstractions).

Are we ok if users can't make elements slightly crooked? If so, it feels nice the way it is.

Thoughts @xmatthewx?

**Comment by xmatthewx** [comment]
This just happens on two-finger drag, yes? If so, I think your implementation is good.
